name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend-build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Front

    steps:

      - name: Set up Node.js
        with:
          node-version: '21'

      - name: Install dependencies
        run: npm ci

      - name: Run Angular unit tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless

      - name: Build Angular app
        run: npm run build

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: sanalyz
          POSTGRES_PASSWORD: sanalyz
          POSTGRES_DB: sanalyz
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s

    steps:

      - name: Set up JDK 21
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Set up Maven
        with:
          maven-version: '3.9.6'

      - name: Run tests
        run: mvn test
        working-directory: API

  gh-pages-deploy:
    runs-on: ubuntu-latest
    needs: frontend-build-and-test

    steps:

      - name: Set up Node.js
        with:
          node-version: '20'

      - name: Build Angular app
        run: |
          npm ci
          npm run build
        working-directory: Front

      - name: Deploy to GitHub Pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: Front/dist/Sanalyz

  deploy:
    runs-on: ubuntu-latest
    needs: [test, frontend-build-and-test, gh-pages-deploy]

    steps:

      - name: Set up JDK 21
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Final deployment
        run: echo "Deployment done"
